language: python
env:
  - GAE_SDK=./gae_sdk
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: ./run_tests
before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.6.zip -nv -O gae_sdk.zip
  - unzip -q gae_sdk.zip
  - mv google_appengine gae_sdk
