language: python
env:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then CMD=server/apptest.py $GAE_SDK; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then CMD=nosetests-3.3; fi

python:
  - "2.7"
  - "3.3"

install: 
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install -r server_requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then pip install -r client_requirements.txt; fi

script: 
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then FLASK_CONF=TEST python $CMD; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then $CMD; fi

before_script:
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.8.zip -nv -O gae_sdk.zip
  - unzip -q gae_sdk.zip
  - mv google_appengine gae_sdk
  - export GAE_SDK=$PWD/gae_sdk
  - export PATH=$PATH:$GAE_SDK
  - export PYTHONPATH=$PYTHONPATH:$GAE_SDK
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then python server/app/generate_keys.py; fi
