language: python

env:
  - CMD=server/apptest.py GAE_VERSION=1.9.23

python:
  - "2.7"

install:
  - pip install -r server_requirements.txt

script:
  - FLASK_CONF=TEST coverage run --source=server $CMD --sdk_location $GAE_SDK --quiet

before_script:
  - bash server/before_script.sh

after_success:
  - coveralls
  
sudo: false

cache:
  directories:
  - /home/travis/virtualenv/python2.7.9/