language: python
env:
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: ./run_tests $GAE_SDK
before_script:
  - mysql -u root -e 'create database okpy; create database okpytest'
  - mysql -u root -e "create user 'development'@'localhost' identified by 'develpp11pp'"
  - mysql -u root -e "grant all privileges on *.* to 'development'@'localhost'; flush privileges"
  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.6.zip -nv -O gae_sdk.zip
  - unzip -q gae_sdk.zip
  - mv google_appengine gae_sdk
  - export GAE_SDK=$PWD/gae_sdk
  - export PATH=$PATH:$GAE_SDK
  - export PYTHONPATH=$PYTHONPATH:$GAE_SDK
  - python server/app/generate_keys.py
  - cd server; python alembic/create_all.py
  - cd ..
