language: python

env:
  - SERVER_ENV=dev

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install pip --upgrade
  - make env
  - source env/bin/activate

script:
  - make test

before_script:
  - manage.py createdb

after_success:
  - coveralls
  - coveralls debug

sudo: false

cache:
  directories:
  - /home/travis/virtualenv/python2.7.9/
