application: okpy-server
version: prod
runtime: python27
api_version: 1
threadsafe: false

default_expiration: 7d  # This is good for images, which never change

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.application

builtins:
- appstats: on
- remote_api: on
- deferred: on

libraries:
- name: django
  version: 1.5

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
